# Generated by Django 6.0.2 on 2026-03-03 21:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50, unique=True, verbose_name='Tag Number')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Animal Name')),
                ('cattle_type', models.CharField(choices=[('DAIRY', 'Dairy Cattle'), ('BEEF', 'Beef Cattle'), ('DUAL', 'Dual Purpose')], default='DAIRY', max_length=10)),
                ('breed', models.CharField(choices=[('HF', 'Holstein Friesian'), ('JF', 'Jersey'), ('BS', 'Brahman'), ('LM', 'Limousin'), ('AG', 'Angus'), ('LOC', 'Local'), ('MIX', 'Mixed')], max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=10, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('distinctive_marks', models.TextField(blank=True)),
                ('acquisition_type', models.CharField(choices=[('BORN', 'Born on Farm'), ('PURCHASED', 'Purchased'), ('GIFT', 'Received as Gift')], default='BORN', max_length=10)),
                ('acquisition_date', models.DateField(default=django.utils.timezone.now)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.CharField(blank=True, help_text='Barn/Shed/Paddock location', max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('DECEASED', 'Deceased'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', max_length=20)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattle_created', to=settings.AUTH_USER_MODEL)),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_dam', to='dairy.cattle', verbose_name='Mother')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_sire', to='dairy.cattle', verbose_name='Father')),
            ],
            options={
                'verbose_name_plural': 'Cattle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField()),
                ('breeding_method', models.CharField(help_text='Natural/AI', max_length=100)),
                ('pregnancy_check_date', models.DateField(blank=True, null=True)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('expected_calving_date', models.DateField(blank=True, null=True)),
                ('actual_calving_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BRED', 'Bred'), ('CONFIRMED', 'Pregnancy Confirmed'), ('CALVED', 'Calved'), ('FAILED', 'Failed/Aborted')], default='BRED', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cattle', models.ForeignKey(limit_choices_to={'gender': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='dairy.cattle')),
                ('offspring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='born_from', to='dairy.cattle')),
                ('sire', models.ForeignKey(limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_offspring', to='dairy.cattle')),
            ],
            options={
                'ordering': ['-breeding_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('feed_type', models.CharField(choices=[('GRAIN', 'Grain Mix'), ('HAY', 'Hay'), ('SILAGE', 'Silage'), ('CONCENTRATE', 'Concentrate'), ('MINERALS', 'Minerals/Supplements'), ('MILK', 'Milk (for calves)')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in kg', max_digits=10)),
                ('feed_time', models.TimeField()),
                ('feed_quality', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Excellent')], default=3)),
                ('notes', models.TextField(blank=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='dairy.cattle')),
                ('fed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-feed_time'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_type', models.CharField(choices=[('CHECKUP', 'Regular Checkup'), ('VACCINATION', 'Vaccination'), ('TREATMENT', 'Treatment'), ('SURGERY', 'Surgery'), ('PREGNANCY', 'Pregnancy Check'), ('DISEASE', 'Disease/Illness')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('diagnosis', models.CharField(max_length=500)),
                ('treatment', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True, help_text='Medications prescribed')),
                ('veterinarian', models.CharField(max_length=200)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('treatment_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='dairy.cattle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_type', models.CharField(choices=[('FMD', 'Foot and Mouth Disease'), ('BQ', 'Black Quarter'), ('HS', 'Hemorrhagic Septicemia'), ('BRU', 'Brucellosis'), ('IBR', 'Infectious Bovine Rhinotracheitis')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='dairy.cattle')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('session', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in liters', max_digits=10)),
                ('fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quality_notes', models.TextField(blank=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in °C', max_digits=4, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(limit_choices_to={'cattle_type__in': ['DAIRY', 'DUAL']}, on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='dairy.cattle')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-session'],
                'unique_together': {('cattle', 'date', 'session')},
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('daily_gain', models.DecimalField(blank=True, decimal_places=2, help_text='Daily weight gain in kg', max_digits=8, null=True)),
                ('age_in_days', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='dairy.cattle')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('cattle', 'date')},
            },
        ),
    ]
