# Generated by Django 6.0.2 on 2026-03-04 18:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('total_milk_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cattle_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_other_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_feed_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_health_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_labor_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Return on Investment %', max_digits=6)),
                ('total_milk_produced', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_daily_milk', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calves_born', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.AddField(
            model_name='cattle',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated current value', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cattle',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total money invested in this cattle', max_digits=12),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='cost_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationschedule',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='feed_type',
            field=models.CharField(blank=True, choices=[('GRAIN', 'Grain Mix'), ('HAY', 'Hay'), ('SILAGE', 'Silage'), ('CONCENTRATE', 'Concentrate'), ('MINERALS', 'Minerals/Supplements'), ('MILK', 'Milk (for calves)')], default='GRAIN', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='CattleSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_contact', models.CharField(blank=True, max_length=100)),
                ('payment_received', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_record', to='dairy.cattle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('MOBILE', 'Mobile Banking'), ('CHEQUE', 'Cheque')], default='CASH', max_length=10)),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='dairy.cattle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dairy.expensecategory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('investment_type', models.CharField(choices=[('INFRASTRUCTURE', 'Infrastructure'), ('EQUIPMENT', 'Equipment'), ('CATTLE', 'Cattle Purchase'), ('LAND', 'Land'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='dairy.cattle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MilkSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in liters', max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('sale_type', models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail'), ('DIRECT', 'Direct Customer')], default='RETAIL', max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_received', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('milk_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cattle_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('feed_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('health_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labor_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_milk_produced', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_milk_per_cow', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
