# Generated by Django 6.0.2 on 2026-02-15 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('average_growth_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_in_acres', models.FloatField()),
                ('water_source', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.FloatField()),
                ('harvest_date', models.DateField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.fishspecies')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.pond')),
            ],
        ),
        migrations.CreateModel(
            name='FishSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_date', models.DateField()),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.harvest')),
            ],
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dead', models.IntegerField()),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.fishspecies')),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.pond')),
            ],
        ),
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=100)),
                ('quantity_kg', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.pond')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('stocking_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.pond')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.fishspecies')),
            ],
        ),
    ]
