# Generated by Django 6.0.2 on 2026-03-03 21:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FisheryFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_fish_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_feed_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_medicine_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Fishery Financial Report',
                'verbose_name_plural': 'Fishery Financial Reports',
            },
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('average_growth_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_in_acres', models.FloatField()),
                ('water_source', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocking_date', models.DateField(default=django.utils.timezone.now)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('initial_avg_weight', models.FloatField(help_text='Weight in grams')),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed')], default='Running', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.pond')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=100)),
                ('quantity_kg', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.pond')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='fishery.productioncycle')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fishery.productioncycle')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('stocking_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='fishery.pond')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='fishery.fishspecies')),
            ],
            options={
                'ordering': ['-stocking_date'],
            },
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dead', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortalities', to='fishery.productioncycle')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortalityrecord_set', to='fishery.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.PositiveIntegerField()),
                ('harvest_date', models.DateField()),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='fishery.productioncycle')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_set', to='fishery.stock')),
            ],
        ),
        migrations.CreateModel(
            name='FishSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.PositiveIntegerField()),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='fishery.harvest')),
            ],
            options={
                'ordering': ['-sale_date'],
                'indexes': [models.Index(fields=['sale_date'], name='fishery_fis_sale_da_c4a74c_idx')],
            },
        ),
    ]
