# Generated by Django 6.0.2 on 2026-02-18 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-stocking_date']},
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='pond',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='species',
        ),
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='pond',
        ),
        migrations.RemoveField(
            model_name='mortalityrecord',
            name='species',
        ),
        migrations.AddField(
            model_name='harvest',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvest_set', to='fishery.stock'),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortalityrecord_set', to='fishery.stock'),
        ),
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quantity_kg',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mortalityrecord',
            name='quantity_dead',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='fishery.pond'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='fishery.fishspecies'),
        ),
    ]
