# Generated by Django 6.0.2 on 2026-02-21 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishery', '0002_alter_stock_options_remove_harvest_pond_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fishsale',
            options={'ordering': ['-sale_date']},
        ),
        migrations.RemoveField(
            model_name='fishsale',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='fishsale',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='fishsale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fishsale',
            name='quantity_kg',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='fishsale',
            name='harvest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='fishery.harvest'),
        ),
    ]
