# Generated by Django 6.0.2 on 2026-02-23 04:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishery', '0003_alter_fishsale_options_remove_fishsale_buyer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocking_date', models.DateField(default=django.utils.timezone.now)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('initial_avg_weight', models.FloatField(help_text='Weight in grams')),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed')], default='Running', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.pond')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishery.fishspecies')),
            ],
        ),
        migrations.AddField(
            model_name='feedrecord',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishery.productioncycle'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishery.productioncycle'),
        ),
        migrations.AddField(
            model_name='mortalityrecord',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fishery.productioncycle'),
        ),
    ]
