# Generated by Django 6.0.2 on 2026-02-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishery', '0004_productioncycle_feedrecord_cycle_harvest_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedrecord',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='fishery.productioncycle'),
        ),
        migrations.AlterField(
            model_name='fishsale',
            name='quantity_kg',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fishery.productioncycle'),
        ),
        migrations.AlterField(
            model_name='mortalityrecord',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortalities', to='fishery.productioncycle'),
        ),
    ]
