# Generated by Django 6.0.2 on 2026-02-24 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishery', '0005_alter_feedrecord_cycle_alter_fishsale_quantity_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='fishery.productioncycle'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fishery.productioncycle')),
            ],
        ),
    ]
