# Generated by Django 6.0.2 on 2026-02-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishery', '0006_alter_harvest_cycle_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisheryFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_fish_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_feed_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_medicine_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Fishery Financial Report',
                'verbose_name_plural': 'Fishery Financial Reports',
            },
        ),
    ]
