# Generated by Django 6.0.2 on 2026-02-26 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishery', '0007_fisheryfinancialreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishsale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='fishsale',
            index=models.Index(fields=['sale_date'], name='fishery_fis_sale_da_c4a74c_idx'),
        ),
    ]
